export const ProductTypes = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
  SET_CATEGORIES: "SET_CATEGORIES",
  UPDATE_FILTERS: "UPDATE_FILTERS",
};
